In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv("housing.proper.csv")
data

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,y
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

Note this project was originally done in R. This is a book for giving the final results of the regression analysis, identifying multicolinearity, and a log transformation.

In [62]:
# model from the R project
# fit5 <- lm(log(train$y) ~ x6 + x7 + x8 + x10 + x11 + x12 + x13, data = train)
X = data[['x6','x7', 'x8', 'x10', 'x11', 'x12', 'x13']]
X_all = data.drop(['y'], axis=1)

Y = pd.DataFrame(np.log(data['y']))

xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.80, random_state=100)
x_all_train, x_all_test, y_all_train, y_all_test = train_test_split(X_all, Y, test_size=0.80, random_state=100)

In [76]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

fit5_all = LinearRegression().fit(x_all_train, y_all_train)
y_all_pred = fit5_all.predict(x_all_test)

mse_all = metrics.mean_squared_error(y_all_pred, y_all_test)

round(mse_all,6)

0.041462

In [77]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

fit5 = LinearRegression().fit(xtrain, ytrain)
y_pred = fit5.predict(xtest)

mse = metrics.mean_squared_error(ytest, y_pred)

round(mse, 6)

0.049669

In [82]:
# change of removing the variables
round(mse - mse_all,3)

0.008



Our model has a mean squared error of approximately 5%. This model considers reducing the variables that have significant multicolinearity and litle effect to explaining the data's variance. 

We were able to reduce the number of variables to 7 key features. By removing 6 variables the mean squared error had changed by less than 1%. Since there was no significant change in mean squared error and had simplified our model, therefore we have a good model which we can use to make predictions with 5% of error on average.


Therefore on average, we can make accurate predictions 95% of the time.